# Stubs for numbers (Python 3.5)

from typing import Any, Hashable, Optional, Union 

class Number(Hashable):
    def __hash__(self) -> int: ...

class Complex(Number):
    def __complex__(self) -> 'Complex': ...
    def __bool__(self) -> bool: ...
    @property
    def real(self) -> 'Real': ...
    @property
    def imag(self) -> 'Real': ...
    def __add__(self, other: 'Complex') -> 'Complex': ...
    def __radd__(self, other: 'Complex') -> 'Complex': ...
    def __neg__(self) -> 'Complex': ...
    def __pos__(self) -> 'Complex': ...
    def __sub__(self, other: 'Complex') -> 'Complex': ...
    def __rsub__(self, other: 'Complex') -> 'Complex': ...
    def __mul__(self, other: 'Complex') -> 'Complex': ...
    def __rmul__(self, other: 'Complex') -> 'Complex': ...
    def __truediv__(self, other: 'Complex') -> 'Complex': ...
    def __rtruediv__(self, other: 'Complex') -> 'Complex': ...
    def __pow__(self, exponent: 'Complex') -> 'Complex': ...
    def __rpow__(self, base: 'Complex') -> 'Complex': ...
    def __abs__(self) -> 'Complex': ...
    def conjugate(self) -> 'Complex': ...
    def __eq__(self, other: object) -> bool: ...

class Real(Complex):
    def __float__(self) -> float: ...
    def __trunc__(self) -> 'Integral': ...
    def __floor__(self) -> 'Integral': ...
    def __ceil__(self) -> 'Integral': ...
    def __round__(self, ndigits: Optional[int] = None) -> Union['Integral', 'Real']: ...
    def __divmod__(self, other: 'Real') -> 'Real': ...
    def __rdivmod__(self, other: 'Real') -> 'Real': ...
    def __floordiv__(self, other: 'Real') -> 'Integral': ...
    def __rfloordiv__(self, other: 'Real') -> 'Integral': ...
    def __mod__(self, other: 'Real') -> 'Real': ...
    def __rmod__(self, other: 'Real') -> 'Real': ...
    def __lt__(self, other: 'Real') -> bool: ...
    def __le__(self, other: 'Real') -> bool: ...

class Rational(Real):
    @property
    def numerator(self) -> 'Integral': ...
    @property
    def denominator(self) -> 'Integral': ...

class Integral(Rational):
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __pow__(self, exponent: 'Complex', modulus: Optional['Integral'] = None) -> 'Complex': ...
    def __lshift__(self, other: 'Integral') -> 'Integral': ...
    def __rlshift__(self, other: 'Integral') -> 'Integral': ...
    def __rshift__(self, other: 'Integral') -> 'Integral': ...
    def __rrshift__(self, other: 'Integral') -> 'Integral': ...
    def __and__(self, other: 'Integral') -> 'Integral': ...
    def __rand__(self, other: 'Integral') -> 'Integral': ...
    def __xor__(self, other: 'Integral') -> 'Integral': ...
    def __rxor__(self, other: 'Integral') -> 'Integral': ...
    def __or__(self, other: 'Integral') -> 'Integral': ...
    def __ror__(self, other: 'Integral') -> 'Integral': ...
    def __invert__(self) -> 'Integral': ...
